name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8.x, 11.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit Tests
        if: (github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master') || !startsWith(env.JAVA_HOME, '/opt/hostedtoolcache/jdk/8')
        run: mvn -V test
      - name: Deploy to sonatype-snapshots
        if: github.ref == 'refs/heads/develop' && startsWith(env.JAVA_HOME, '/opt/hostedtoolcache/jdk/8')
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          set -e
          cat > settings.xml <<EOF
          <settings>
            <servers>
              <server>
                 <id>sonatype-snapshots</id>
                 <username>${SONATYPE_USERNAME}</username>
                 <password>${SONATYPE_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF
          ./mvnw -V deploy -s settings.xml -DskipTests=true -DserverId=sonatype-snapshots
      - name: Deploy to sonatype-releases
        if: github.ref == 'refs/heads/master' && startsWith(env.JAVA_HOME, '/opt/hostedtoolcache/jdk/8')
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
          GPG_DIR: ${{ secrets.GPG_DIR }}
        run: |
          set -e
          docker run \
            --rm \
            -v /tmp:/tmp \
            -e ENCRYPTION_PASSWORD=${ENCRYPTION_PASSWORD} \
            making/encrypted-gpg /tmp

          cat > settings.xml <<EOF
          <settings>
            <servers>
              <server>
                 <id>sonatype-releases</id>
                 <username>${SONATYPE_USERNAME}</username>
                 <password>${SONATYPE_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

          ./mvnw javadoc:jar \
              source:jar \
              package \
              org.apache.maven.plugins:maven-gpg-plugin:1.6:sign \
              org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy \
              -s settings.xml \
              -Dgpg.executable=gpg \
              -Dgpg.keyname=${GPG_KEYNAME} \
              -Dgpg.passphrase=${GPG_PASSPHRASE} \
              -Dgpg.defaultKeyring=false \
              -Dgpg.publicKeyring=/tmp/pubring.gpg \
              -Dgpg.secretKeyring=/tmp/secring.gpg \
              -DserverId=sonatype-releases \
              -DnexusUrl=https://oss.sonatype.org \
              -DautoReleaseAfterClose=true \
              -DaltDeploymentRepository=sonatype-releases::default::https://oss.sonatype.org/service/local/staging/deploy/maven2 \
              -DskipTests=true